### ISSUE TITLE
Transfer project back to personal GitHub

### ISSUE THREAD

**Issue by Rel1cx** [Rel1cx/eslint-react#116]
<img width="891" alt="image" src="https://github.com/eslint-react/eslint-react/assets/24217275/71257482-01d7-4660-90f5-3928c8e5203c">

It looks like we're going to run out of free Netlify credit in just a few days, and I need to transfer the project back to a personal GitHub so we can use Vercel without having to buy a paid team plan, and a lot of other services require a paid plan for projects under the organization, which I don't have the money to pay for at the moment.

**Comment by JounQin** [comment]
I'm surprised this project is transferred back to personal account for this reason, actually:

1. You can apply https://www.netlify.com/legal/open-source-policy/
2. You can link org project with your personal Vercel account, and use https://github.com/amondnet/vercel-action for deployment, take https://github.com/un-ts/lib-boilerplate/blob/main/.github/workflows/vercel.yml as example

**Comment by SukkaW** [comment]
@Rel1cx Or you can just use Cloudflare Pages:

- Unlimited bandwidth
- 500 build minutes monthly (200 more than Cloudflare)

Also, we can just do builds on GitHub Actions (unlimited build minutes for open-source projects under acceptable usage) and deploy the dist to Cloudflare Pages.

**Comment by Rel1cx** [comment]
@JounQin @SukkaW Thanks for the suggestions but I'll keep it under personal account until there's an obvious need to transfer it to the organisation.

**Comment by JounQin** [comment]
@Rel1cx The greatest part of organization is collaboration and permission model, but if want to maintain this project solo, that's totally fine, while I'll never consider.
