### ISSUE TITLE
[docs] How is this plugin related to eslint-plugin-react?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [Rel1cx/eslint-react#327]
I can see many rules are the same as [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react) rules.

What is the purpose of @eslint-react/eslint-plugin compared to eslint-plugin-react?

What are the differences between @eslint-react/eslint-plugin and eslint-plugin-react?

**Comment by Rel1cx** [comment]
Hi there! I expanded on your question a little.

The purpose of `eslint-react` is to provide a platform for creating ESLint rules for not just for ReactDOM but also other libraries and frameworks that use React as a runtime.

### What are the differences between `@eslint-react/eslint-plugin` and `eslint-plugin-react`?

The main difference is when using `@eslint-react/eslint-plugin` you can customize the behavior of the rules depending on the what render target you are using. While `eslint-plugin-react` will always assume you are using React DOM even if you are working with a project that only uses React Three Fiber.

### Is `@eslint-react/eslint-plugin` a replacement for `eslint-plugin-react`?

No, `@eslint-react/eslint-plugin` is not meant to be a drop-in replacement for `eslint-plugin-react`. But you can still using it as a replacement if you want to. Just keep in mind that some rules may behave differently, the rules provided by `@eslint-react/eslint-plugin` are designed to be more strict than `eslint-plugin-react`.

**Comment by EvgenyOrekhov** [comment]
Thank you!
