### ISSUE TITLE
Changelog generator and auto-publishing solution

### ISSUE THREAD

**Issue by Rel1cx** [Rel1cx/eslint-react#42]

**Comment by Rel1cx** [comment]
At present, I prefer to use https://github.com/changesets/changesets

**Comment by hyoban** [comment]
You can also take a look at https://github.com/unjs/changelogen

**Comment by Rel1cx** [comment]
> You can also take a look at [unjs/changelogen](https://github.com/unjs/changelogen)

Thanks for the suggestion I'll take a look at it, I'm focusing on implementing the rest of the rules in https://github.com/eslint-react/eslint-react/issues/85 first, I won't be adding the changelog generator until 1.0 because there will be a lot of changes, but in the meantime the plugin isn't officially released.
