### ISSUE TITLE
[feat] no-class-component - allow componentDidCatch

### ISSUE THREAD

**Issue by christopher-buss** [Rel1cx/eslint-react#495]
### Describe the problem

If I implement a class component with a componentDidCatch method (namely for ErrorBoundary classes), I still get a `Do not use class components. Use function components instead.` error.

### Describe the solution you'd like

I would like this rule to ignore any ReactComponent that implements the componentDidCatch method.

### Additional context

https://www.npmjs.com/package/eslint-plugin-react-prefer-function-component

A plugin that supports this behaviour is listed above.

**Comment by Rel1cx** [comment]
Makes sense, expect this to be supported in the next release.
