### ISSUE TITLE
[feat] polymorphic prop

### ISSUE THREAD

**Issue by huynhducduy** [Rel1cx/eslint-react#669]
### Describe the problem

We have a custom element that can dynamically act like a dom element, for example:

```js
<VisuallyHidden as='button'>Submit</VisuallyHidden>
```

We want to run `eslint-react`'s DOM related rules against it as well.

### Describe the solution you'd like

I noticed the `additionalComponents` config, but currently seems like there is no way to set the `as` dynamically based on the `selector` (like in regular expression). But even if we do have a way, the `polymorphicPropName` like in `eslint-plugin-jsx-a11y` would be so much easier to understand and use. Reference: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#configurations

```json
{
  "settings": {
    "jsx-a11y": {
      "polymorphicPropName": "as"
    }
  }
}
```

**Comment by Rel1cx** [comment]
Nice suggestion, it will be supported in the next version!
