### ISSUE TITLE
[feat] instead of providing `react-hooks-extra`, refactor the base `eslint-plugin-react-hooks` into v9/`typescript-eslint`

### ISSUE THREAD

**Issue by pauliesnug** [Rel1cx/eslint-react#710]
### Describe the problem

Right now, there is a tracking issue for ESLint v9 support for React // https://github.com/facebook/react/issues/28313
This issue has been open for months with seemingly little progress, and seeing as the plugin only provides two rules, where as `eslint-react` provides addons for the react-hooks plugin and many other react ESLint rules, it might make sense to add the two rules present in the base plugin into a new `eslint-react` section.

### Describe the solution you'd like

We could just refactor the current `eslint-plugin-react-hooks` and add a new `eslint-react` module named `react-hooks` with the same/improved functionality of the current plugin, with v9 support etc.

**Comment by Rel1cx** [comment]
https://github.com/facebook/react/issues/28313#issuecomment-2076798972
I have learned that support for `eslint-plugin-react-hooks` in ESLint v9 has been released in the canary channel and will be released as a stable version along with React 19. This means that after the stable release, `eslint-plugin-react-hooks` in `eslint-react` will become obsolete, turning this integration into a temporary workaround. Once the official stable version is released, users will have to face the choice again and incur unnecessary migration costs, which is not what we want to see.

Additionally, the official `eslint-plugin-react-hooks` and the `eslint-plugin-react-hooks-extra` in `eslint-react` have distinct and different positioning. Merging them into one plugin will confuse their original roles.

**Comment by pauliesnug** [comment]
Okay, thanks for the swift response, I'll look into that

**Comment by wong2** [comment]
The current suggestion is use both `eslint-plugin-react-hooks@canary` and `eslint-plugin-react-hooks-extra`, right?

**Comment by pauliesnug** [comment]
> The current suggestion is use both `eslint-plugin-react-hooks@canary` and `eslint-plugin-react-hooks-extra`, right?

@wong2 That's what I ended up doing until `@next` is stabilized with React 19
