### ISSUE TITLE
[bug] xxx-shorthand-boolean ruls don't work

### ISSUE THREAD

**Issue by Semigradsky** [Rel1cx/eslint-react#824]
### Describe the bug

I tried to add `@eslint-react/prefer-shorthand-boolean` or `@eslint-react/avoid-shorthand-boolean` to legacy config, but I don't see any effect. I can write `<input disabled />` or `<input disabled={true} />` without any errors.

### Reproduction

Any repo with configured plugins which I can fork?

### Platform and versions

```Text
@eslint-react/eslint-plugin = 1.14.2
```

**Comment by michaelfaith** [comment]
Do you happen to have a reproduction of this?
