### ISSUE TITLE
[docs] links are unclickable on mobile

### ISSUE THREAD

**Issue by dougludlow** [Rel1cx/eslint-react#828]
I’m attempting to browse the docs site on my iPhone and I noticed that all links below the menu appear to be unclickable. I haven’t been able to check on a desktop/laptop yet with dev tools, but there appears to be an invisible element in the way. I can’t even select text. 

I’ve tried both Brave and Safari and get the same result.

**Comment by Rel1cx** [comment]
This appears to be a bug in nextra, which can be reproduced at https://nextra.site/docs/docs-theme/start.
