### ISSUE TITLE
[bug] [eslint-plugin-react-web-api] no-leaked-event-listener

### ISSUE THREAD

**Issue by rogepi** [Rel1cx/eslint-react#842]
### Describe the bug

The `no-leaked-event-listener` rule does not recognize traversing an array of event types.

```typescript
import { useEffect } from "react";

export function Component() {
  useEffect(() => {
    const events: Array<keyof DocumentEventMap> = [
      "mousedown",
      "mousemove",
      "keypress",
      "scroll",
      "touchstart",
    ];
    const handler = () => {};

    events.forEach((event) => {
      document.addEventListener(event, handler);  //A 'addEventListener' in 'useEffect' should have a corresponding 'removeEventListener' in its cleanup function 
    });

    return () => {
      events.forEach((event) => {
        document.removeEventListener(event, handler);
      });
    };
  }, []);
}
```

Or is this not recommended?👀

### Platform and versions

```Text
node: v20.16.0
typescript: ^5.6.3
eslint: ^9.12.0
@eslint-react: 1.15.1-next.0
```

**Comment by rakleed** [comment]
Reproduction just in case: https://eslint-online-playground.netlify.app/#eNqVUtuO0zAQ/RXLL+1WWZfsimUpWgSCviHxAU2RvM4kNevYke30oir/zthx2gACwUsy4zkz53h8ztRZsYQjb1oF7LujKyqb1lhPzqRzsK4qEJ70pLKmIQW1wIUv6LtCFxqOESeMdp58MtilQXvyROY35Ok9OReapCLsseCwsiloY3BsY/ZQ0AwHxrQ0Bz2kL3C6Jk5Yo9QQe9OJnfPcIvs20o/Dd1yXCj4KL/fSn670fUJdbjGf6CJJE6uMXXOxm89jPgUQcpAaxTBelutQ/CKdBw12gGa/EN8gXWjqQzCEFnxn9XQd/0h8obZxU//BnvhjEP99RjbbUVISpDul8CQAaEbBKak9w2VWsv7JAfGxh5effRhgt/FsmZJWdbXUM5yTOmplnrlyqSdloX5xSwkV75RHJ0Q9OCwxO7ysME0DuoQyC9W0jkoqcCuymS0WywXqm2VkDI+zbUQSoriuO17D19ZLdMXqusskYnJCCGMsHbNnaw4ObBoT9pW2F//hG9yGa2q5eEECZDUaVxSnoS1PLRp5FY1cdiqYeiiU0IabaCHBBUBiL2giHpq+5a9Zfs9epbZQjzu5LU0zIh7ZPct/A1jTebAT3AO7ewyDRtmDiP3nP+n4y4OOzCx/w+4mzAMoVd+y/OHCh2ai/Q+lwGGa

**Comment by rakleed** [comment]
@Rel1cx here is one more false positive: https://eslint-online-playground.netlify.app/#eNqVUk2P0zAQ/SsjX/qh1KVULEvRIhDsDYkLt6ZIbjJpzTp2ZDvdVlX/O2PH6cciEFwSj+fNvOeZd2TOFlPci7pRyH86tmCyboz1cITW4WNVYeHhBJU1NeTMoih8zt7nOte4j7jCaOfhs6EqjdrDAwxH8PABjrmGlMQdJRxlljmrDbWtzQ5zllHDGJbmWXfhEx4ugSusUao7e9MWW+eFJfZVpO+bb4UuFX4qvNxJf7jQnxLq/IrhlS6AylgYXskDUyWdox4CsFFmLdT3rXRclOVjSH+VzqNGO4zg7AX9iEhDYU8OYNG3Vl/P5J/Zb/htHNp/SOhEXP6nDJarkAxBUqVbpegmAFjG0CmpPSdZldzceCGuvfPA4GMHm8S7aQoa1W6kHlCfVNEpd6kmRSF/9k2JlWiVJ09EPdQsMYe3FqauUZdYZiHbr0wqdAtYDsbj6Zj0DTLoj/vBKiIBlNCbVmzwW+MlzXfxcpnXNwCc83TN19Y8O7SpTZhXml78h2/wHY2pEcUTERCr0TSi2I0MemjI0oto6bJVwd5dosQmvEQXEl0AJPacJeKu6MfsDZ/N+atUFvJxJpPS1D3ins/57DeANa1He4W746/vQ6Nedidi9+VPOv6y0J6Zz97y+WSNXtwI6LAJ9I7P7s605Cl2+gUK6GiH
